In [1]:
DATA_PATH = "../data/raw/train-*.parquet"

In [2]:
import polars as pl
import duckdb

df = pl.scan_parquet(DATA_PATH).collect()

print(f"Total baris data: {df.height}")
print(f"Total kolom: {df.width}")

display(df.head())

Total baris data: 370067
Total kolom: 15

shape: (5, 15)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ news_title ┆ news_sour ┆ news_auth ┆ … ┆ update_da ┆ create_da ┆ news_guid ┆ news_raw_ │
│ ---     ┆ ---        ┆ ce        ┆ or        ┆   ┆ te        ┆ te        ┆ ---       ┆ data      │
│ str     ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│         ┆            ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1924973 ┆ Dana       ┆ https://r ┆ Wahyudi   ┆ … ┆ 2026-04-2 ┆ null      ┆ CBMiswFBV ┆ {'id':    │
│         ┆ Kegiatan   ┆ adarutara ┆           ┆   ┆ 7 03:08:5 ┆           ┆ V95cUxOaD ┆ None,     │
│         ┆ Isbat      ┆ .disway.i ┆           ┆   ┆ 0.074774+ ┆           ┆ hvMVNUZFR ┆ 'url':    │
│         ┆ Nikah      ┆ d/m…      ┆           ┆   ┆ 00:…      ┆           ┆ lel…      ┆ 'https:// │
│         ┆ Baka…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ r…        │
│ 1925951 ┆ Satu Orang ┆ https://w ┆ Iswanto   ┆ … ┆ 2026-04-2 ┆ null      ┆ CBMimgFBV ┆ {'id':    │
│         ┆ Meninggal  ┆ ww.ayokal ┆           ┆   ┆ 7 05:26:2 ┆           ┆ V95cUxQSk ┆ None,     │
│         ┆ dari Insi… ┆ tim.com/s ┆           ┆   ┆ 0.891514+ ┆           ┆ NndGh1VGx ┆ 'url':    │
│         ┆            ┆ atu…      ┆           ┆   ┆ 00:…      ┆           ┆ Oek…      ┆ 'https:// │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ w…        │
│ 1925952 ┆ DPRD       ┆ https://i ┆ Emmy      ┆ … ┆ 2026-04-2 ┆ null      ┆ CBMirwFBV ┆ {'id':    │
│         ┆ Bongkar    ┆ nfosatu.c ┆ Haryanti  ┆   ┆ 7 05:26:2 ┆           ┆ V95cUxOMF ┆ None,     │
│         ┆ Ketidakses ┆ o/dprd-bo ┆           ┆   ┆ 0.891632+ ┆           ┆ MxOGNOWlZ ┆ 'url':    │
│         ┆ uaian L…   ┆ ngk…      ┆           ┆   ┆ 00:…      ┆           ┆ tT1…      ┆ 'https:// │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ i…        │
│ 1925953 ┆ DPRD       ┆ https://i ┆ Emmy      ┆ … ┆ 2026-04-2 ┆ null      ┆ CBMirwFBV ┆ {'id':    │
│         ┆ Dorong     ┆ nfosatu.c ┆ Haryanti  ┆   ┆ 7 05:26:2 ┆           ┆ V95cUxPMG ┆ None,     │
│         ┆ Penanganan ┆ o/dprd-do ┆           ┆   ┆ 0.891650+ ┆           ┆ daZU9wVTR ┆ 'url':    │
│         ┆ Banjir …   ┆ ron…      ┆           ┆   ┆ 00:…      ┆           ┆ 0ZG…      ┆ 'https:// │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ i…        │
│ 1924974 ┆ Kepung     ┆ https://p ┆ Calvin    ┆ … ┆ 2026-04-2 ┆ null      ┆ CBMi1wFBV ┆ {'id':    │
│         ┆ Pasar      ┆ apuatenga ┆ Eluis     ┆   ┆ 7 03:09:4 ┆           ┆ V95cUxNbH ┆ None,     │
│         ┆ Karang     ┆ h.tribunn ┆ Erari     ┆   ┆ 8.135779+ ┆           ┆ NySlhzMDF ┆ 'url':    │
│         ┆ Nabire,    ┆ ews…      ┆           ┆   ┆ 00:…      ┆           ┆ FV1…      ┆ 'https:// │
│         ┆ Ma…        ┆           ┆           ┆   ┆           ┆           ┆           ┆ p…        │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
profiling_summary = duckdb.query("SUMMARIZE SELECT * FROM df").df()

display(profiling_summary)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,id,VARCHAR,1,99996,368128,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
1,news_title,VARCHAR,""" Danrem 133/NW Tinjau Progres Pembangunan Fas...",🪨 Produksi Batu Bara 2025 dan 2026 Diproyeksi ...,378564,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
2,news_source,VARCHAR,http://aceh.navigasi.co.id/amp/1369597/rekomen...,https://zuper.fajar.co.id/2025/11/25/surya-ins...,385488,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
3,news_author,VARCHAR,( Humas Pemprov Sumsel ),𝗗𝟯𝗹 𝟬𝟮,20397,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.93
4,news_hostname,VARCHAR,1kabar.com,zuper.fajar.co.id,4255,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
5,news_date,VARCHAR,0138-04-26 23:12:23+00:00,2040-04-27 08:56:00+00:00,29000,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.30
6,news_text,VARCHAR,"![ MANADO, BeritaManado.com — Setelah melewati...",🔥 KRITIK LGI MAKIN PEDAS: Realisasi PAD Musi R...,395578,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
7,news_tags,VARCHAR,"[""#KapolresPangandaran;#poldajabar;#PolresPang...",[],294951,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
8,news_kabkot,VARCHAR,Aceh Barat,Yalimo,1021,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
9,news_intent,VARCHAR,"{'derived': {'country': 'Indonesia', 'in_indon...",{'places': [{'region_mentioned': 'Tanjungpinan...,388290,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
10,news_image,VARCHAR,//www.mentawaikita.com/assets/foto/berita/thum...,uang-kertas-rupiah.jpg,274392,<NA>,<NA>,<NA>,<NA>,<NA>,370067,8.09
11,update_date,VARCHAR,2025-10-07 11:27:24.717325+00:00,2026-05-08 14:46:50.892578+00:00,377779,<NA>,<NA>,<NA>,<NA>,<NA>,370067,0.00
12,create_date,VARCHAR,2025-10-07 08:59:33.262308+00:00,2025-12-20 22:35:16.748853+00:00,362597,<NA>,<NA>,<NA>,<NA>,<NA>,370067,7.66
13,news_guid,VARCHAR,0079d9f758359b363899fddd78e17064,ffc30ee746f92a242294a65b52522c2b,28678,<NA>,<NA>,<NA>,<NA>,<NA>,370067,92.34
14,news_raw_data,VARCHAR,"{'id': None, 'url': ""https://kemenagrejanglebo...",{},32038,<NA>,<NA>,<NA>,<NA>,<NA>,370067,81.94